apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: zzzzzzzzzzzzzzzzewoJImF1d2luZGV4LmRvY2tlci5iB7CgkJCSJhdXRoIjogIlltaGhjbUYwYURNd01EWTZTRk5oUDNJMWEyNTRaRVpHYlhOTSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson

#kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=zzzzzzzzz --docker-password=zzzzzzzzz --docker-email=zzzzzzz@gmail.com